aws:elasticbeanstalk:container:python:
   NumProcesses: '1'
   NumThreads: '15'
   WSGIPath: locallibrary/wsgi.py
   eb_codebuild_settings:
    CodeBuildServiceRole: CodeBuildServiceRole
    ComputeType: BUILD_GENERAL1_SMALL